models:
  gpt_4o:
    name: "gpt-4o"
    temperature: 0.0
    max_tokens: 1024
  gpt_4o_mini:
    name: "gpt-4o-mini"
    temperature: 0.0
    max_tokens: 1024
  llama-3.3-70b-versatile:
    name: "llama-3.3-70b-versatile"
    temperature: 0.0
    max_tokens: 1024
    base_url: "https://api.groq.com/openai/v1"
  mixtral-8x7b-32768:
    name: "mixtral-8x7b-32768"
    temperature: 0.0
    max_tokens: 1024
    base_url: "https://api.groq.com/openai/v1"

general:
  api_key: "YOUR_PLACEHOLDER_API_KEY"
  base_url: "https://api.openai.com/v1/"