models:
  gpt_4o:
    name: "gpt-4o"
    temperature: 0.0
    max_tokens: 512
  gpt_4o_mini:
    name: "gpt-4o-mini"
    temperature: 0.0
    max_tokens: 512

general:
  api_key: "YOUR_PLACEHOLDER_API_KEY"
  base_url: "https://api.openai.com/v1/"