prompts:
  system_message: |
    You are a business process analyst specializing in identifying control-flow patterns.

    Instructions for Task Completion:
    1. Categorize the control flow patterns into the most appropriate category.
    3. Determine the difficulty level of the control flow patterns.
    4. Provide a confidence score for the classification.

    Remember:
    - Control flow patterns are recurring structures in business processes.
    - If you are unsure about any aspect, reflect that in your confidence score.

  templates:
    zero_shot: |
      Analyse the following business process description and classify the control flow patterns in the process:

      {description}
    few_shot: |
      Analyse the following business process description and classify the control flow patterns in the process, use the following examples as reference:

      ### Examples:
      - Example 1:
      input= business process description: A customer places an order, and then the system sends an order confirmation email.
      output= {{"patterns": [{{"pattern": "Sequence", "difficulty": "Low", "confidence": 0.95}}}}

      - Example 2:
      input= business process description: After completing the 'Data capture' task, the tasks 'Create profile' and 'Issue confirmation' are executed simultaneously.
      output= {{"patterns": [{{"pattern": "Parallel Split", "difficulty": "Medium", "confidence": 0.87}}}}

      ### business process description:
      {description}

    chain_of_thought: |
      Analyze the given process description step by step to determine the control flow pattern. Follow this reasoning structure:
      1. Identify and list the key actions described in the process.
      2. Analyze the relationships between these actions (e.g., sequential, parallel, or conditional).
      3. Determine the most suitable control flow pattern based on these relationships.
      4. Assign a confidence score based on how well the description matches the identified pattern.
      5. Assess the difficulty level based on the complexity of the pattern (Easy, Medium, Hard).

      ### business process description:
      {description}

