prompts:
  system_message: |
    You are a business process analyst specializing in identifying control-flow patterns.

    Instructions for Task Completion:
    1. Categorize the control flow patterns into the most appropriate category.
    2. Determine the difficulty level of the control flow patterns.
    3. Provide a confidence score for the classification.

    Remember:
    - Control flow patterns are recurring structures in business processes.
    - If you are unsure about any aspect, reflect that in your confidence score.

  templates:
    zero_shot: |
      Analyse the following business process description and classify the control flow patterns in the process:

      Process description:
      {description}

    few_shot: |
      Analyze the following process description and identify the control flow patterns. Use the examples below as a reference:

      Examples:
      - Example 1:
        input: Process description: A customer fills out a registration form, and after submission, a verification email is sent automatically.
        output: {{"patterns": [{{"pattern": "Sequence", "difficulty": "Low", "confidence": 0.95}}]}}

      - Example 2:
        input: Process description: Once the contract is signed, both the onboarding task and account setup task are performed concurrently.
        output: {{"patterns": [{{"pattern": "Parallel Split", "difficulty": "Medium", "confidence": 0.85}}]}}

      - Example 3:
        input= Process description: After the marketing team approves the campaign, the operations and finance teams review the plan together before final approval is granted.
        output= {{"patterns": [{{"pattern": "Synchronization", "difficulty": "High", "confidence": 0.80}}]}}

      - Example 4:
        input: Process description: Depending on the size of the purchase, either a basic approval process or a detailed risk assessment is initiated.
        output: {{"patterns": [{{"pattern": "Exclusive Choice", "difficulty": "Medium", "confidence": 0.88}}]}}

      Process description:
      {description}

    chain_of_thought: |
      Analyze the given process description step by step to determine the control flow pattern. Follow this reasoning structure:
      1. Identify key actions described in the process.
      2. Analyze the relationships between these actions (e.g., sequential, parallel, or conditional).
      3. Determine the most suitable control flow pattern based on these relationships.
      4. Assign a confidence score based on how well the description matches the identified pattern.
      5. Assess the difficulty level based on the complexity of the pattern (Easy, Medium, Hard).

      Process description:
      
      {description}

